### ISSUE TITLE
Static CDN Filters: Embedded Fonts result in Cross-Origin Request Blocked (CORS) error

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#427]
Referencing: http://davidwalsh.name/cdn-fonts
For this reason, I suggest that we blacklist all font extensions by default. We can write a KB article to explain what is needed for fonts to be served cross-domain without issue, or just link to [this article](http://davidwalsh.name/cdn-fonts).

Referencing internal ticket: https://websharks.zendesk.com/agent/tickets/5283

**Comment by raamdev** [comment]
I'm labeling this as a bug since the current default configuration may result in this error message in the browser console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource

**Comment by jaswrks** [comment]
I was just reviewing this again. I was unable to reproduce an issue with `eot`, `woff`, `otf` or `ttf` files. The default set of whitelisted extensions in ZenCache Pro (powered by the WP Media Library) does not include these file types. So for that reason, unless a site owner explicitly enabled these files types, this should not be an issue in the current release.

Having said that. I suggest the following changes:
- Add `eot,ttf,otf,woff` to the default set of whitelisted extensions.
- Add `eot,ttf,otf,woff` to the default set of blacklisted extensions also.

This way enabling fonts requires only that you remove the extensions from your blacklist.

**Comment by jaswrks** [comment]
I've had this corrected. I'll submit a Pull Request once the repo changeover is done.

**Comment by raamdev** [comment]
Currently blocked by the repo changeover.

**Comment by raamdev** [comment]
This has been fixed in the latest development copy and will go out with the next release: 
- **Improvement** (Pro): Updated Static CDN Filters whitelist to exclude font file extensions `eot,ttf,otf,woff`, as they require custom CORS configurations to display properly. See [#427](https://github.com/websharks/zencache/issues/427).
- **Improvement** (Pro): Updated Static CDN Filters blacklist to include font file extensions `eot,ttf,otf,woff`, as they require custom CORS configurations to display properly. See [#427](https://github.com/websharks/zencache/issues/427).

**Comment by jaswrks** [comment]
> Add eot,ttf,otf,woff to the default set of blacklisted extensions also.

I think we goofed here. Fonts are most likely to be referenced by CSS, which is static. So when Static CDN Filters are applied, the CSS is getting moved to the CDN, and the fonts are then expected to live on the CDN too. By excluding them, we are actually creating a problem instead of solving one.

I think the reason I made this call before (i.e., goofed), is that when this change was made, the HTML Compressor was not picking up Static CDN Filters. We improved this later. So now they are, which means that CSS compressed by the HTML Compressor is now served from the CDN. Now that this has been updated, font file extensions can be included by default.

**Comment by raamdev** [comment]
@jaswsinc I just tested uploading a custom font and adding a custom `@font-face` declaration to my `style.css` file, then setting `.entry-title` to use that custom font face. 

I enabled ZenCache Pro v150709, HTML Compressor, and Static CDN Filters, then removed the list of fonts from the Static CDN Filters Blacklisted Extensions. Upon saving and reloading the front-end of the site (from a different, logged-out browser), I still received the Cross-Origin error and the font did not load (using Chrome 43 on Mac OS X).

![2015-07-15_16-16-17](https://cloud.githubusercontent.com/assets/53005/8708905/dc9875f6-2b0c-11e5-86e5-92c630c902ac.png)

![2015-07-15_16-14-51](https://cloud.githubusercontent.com/assets/53005/8708872/b3c5c7e6-2b0c-11e5-9170-23994a425192.png)

I proceeded to inspect the compressed CSS to confirm the URLs to the font files had been rewritten to point at the CDN and sure enough they had:

``` css
@font-face{font-family:'Raleway';src:url('http://d28ql8m1xkpbbr.cloudfront.net/wordpress/wp-content/themes/twentyfifteen/webfonts/raleway_thin-webfont.eot');src:url('http://d28ql8m1xkpbbr.cloudfront.net/wordpress/wp-content/themes/twentyfifteen/webfonts/raleway_thin-webfont.eot#iefix') format('embedded-opentype'),url('http://d28ql8m1xkpbbr.cloudfront.net/wordpress/wp-content/themes/twentyfifteen/webfonts/raleway_thin-webfont.ttf') format('truetype'),url('http://d28ql8m1xkpbbr.cloudfront.net/wordpress/wp-content/themes/twentyfifteen/webfonts/raleway_thin-webfont.woff') format('woff'),url('http://d28ql8m1xkpbbr.cloudfront.net/wordpress/wp-content/themes/twentyfifteen/webfonts/raleway_thin-webfont.svg#Raleway') format('svg');font-weight:normal;font-style:normal}
```

So, it would appear that it's not as simple as removing those font file extensions from the Blacklisted Extension on the Static CDN Filters...

---

---

This is what I added to the bottom of my `style.css` file to have it load the font I uploaded:

``` css
@font-face {
    font-family: 'Raleway';
    src:url('webfonts/raleway_thin-webfont.eot');
    src:url('webfonts/raleway_thin-webfont.eot?#iefix') format('embedded-opentype'),
        url('webfonts/raleway_thin-webfont.ttf') format('truetype'),
        url('webfonts/raleway_thin-webfont.woff') format('woff'),
        url('webfonts/raleway_thin-webfont.svg#Raleway') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Here's how I'm using the font:

``` css
.entry-title {
    font-family: "Raleway" !important;
}
```

Finally, [here's the Raleway font](https://www.theleagueofmoveabletype.com/raleway) in case you want to download and use exactly what I used to test.
